version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_bot_dev
    volumes:
      - account_bot_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - account-bot-networks
volumes:
  account_bot_data:
  
networks:
  account-bot-networks:
    driver: bridge
